# Default values for godaddy-webhook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: dpac4u/ticktip:godaddy
  tag: v0.1.1
  pullPolicy: IfNotPresent

groupName: acme.ticktip.com

certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager

imagePullSecrets:
  - name: dockersecret1
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 443

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
